(define (problem dc_motor_problem) (:domain dc_motor_engineering)
  (:init
    (not (materials_selected))
    (not (dimensions_calculated))
    (not (design_validated))
    (not (assembly_completed))
    (not (testing_done))
    (not (installed))
    (not (maintenance_performed))
    (not (disposed))
  )
  (:goal
    (and
      (materials_selected)
      (dimensions_calculated)
      (design_validated)
      (assembly_completed)
      (testing_done)
      (installed)
      (maintenance_performed)
      (disposed)
    )
  )
)
